mensagem = input("Digite uma mensagem: ")
print("\nMensagem:",mensagem)

print("\nMensagem depois das mudanças:", end=" ")

mensagem = mensagem.replace("a","4")
mensagem = mensagem.replace("A","4")
mensagem = mensagem.replace("b","8")
mensagem = mensagem.replace("B","8")
mensagem = mensagem.replace("e","3")
mensagem = mensagem.replace("E","3")
mensagem = mensagem.replace("o","0")
mensagem = mensagem.replace("O","0")
mensagem = mensagem.replace("s","5")
mensagem = mensagem.replace("S","5")
mensagem = mensagem.replace("t","7")
mensagem = mensagem.replace("T","7")

print(mensagem)
print("\n")